// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace ML__Net_Core_Research__Taxi_Fares_ML.Model
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
